title: kosmotique
theme: jekyll-theme-minimal
logo:  /assets/images/logo.jpg
timezone: Europe/Berlin
future: true

plugins:
- jekyll-feed

collections:
- texts

collections:
  texts:
    output: true

defaults:
-
  scope:
    path: ""
  values:
    layout: "default"
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
